version: '3'
services:
  nginx:
    ports:
      - "${WIKI_PORT}:4433"
  wiki:
    build: 
      context: docker/wikijs
      args:
        - SCRIPT_UID
        - SCRIPT_GID
    environment:
      DB_FILEPATH: /var/lib/wikijs/wikijs.sql
      DB_TYPE: sqlite
    env_file:
      - .env
    volumes:
      - ./config/wiki:/var/lib/wikijs
      - ./config/wiki/data:/wiki/data
    restart: "unless-stopped"
    networks:
      - fvtt
