version: '3'
services:
  nginx:
    depends_on:
      - oauth
  oauth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR: "/var/lib/oauth/templates"
      OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "/var/lib/oauth/${OAUTH_LOGO}"
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: "/var/lib/oauth/authenticated_mails"
      OAUTH2_PROXY_UPSTREAMS: "http://fvtt:${FVTT_PORT}/"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:${OAUTH_PROXY_PORT}"   # do i need to override default of 127.0.0.1 in docker?
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "false"  # reconsider this for multiple providers?
    env_file:
      - .env
    volumes:
      - ./config/oauth:/var/lib/oauth:ro
    restart: "unless-stopped"
    depends_on:
      - fvtt
    networks:
      - fvtt
