version: '3'
services:
  nginx:
    ports:
      - "${WIKI_PORT}:4333"
  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_FILEPATH: /var/lib/wikijs/wikijs.sql
      DB_TYPE: sqlite
    env_file:
      - .env
    volumes:
      - ./config/wiki:/var/lib/wikijs
    restart: "unless-stopped"
    networks:
      - fvtt
