version: '3'
services:

# fvtt breaks on read-only volumes
#
#  fvtt:
#    volumes:
#      - ./mount/data/modules/mymodule:/var/lib/fvtt/Data/data/modules/mymodule:ro

  nginx:
    ports:
      - "${NGINX_LOCAL_PORT}:8000"
